python-lib/prologin/concours/stechec/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from prologin.concours.stechec.forms import LoginForm
from prologin.concours.stechec import views

urlpatterns = [
    url(r'^$', (TemplateView.as_view(template_name='stechec/home.html')), name="home"),

    url(r'^login/$', auth_views.login, {'template_name': 'stechec/login.html', 'authentication_form': LoginForm}, name="login"),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name="logout"),

    url(r'^ask-help/$', views.AskForHelp.as_view(), name='ask-for-help'),
    url(r'^ask-help/list/$', views.AskForHelpList.as_view(), name='ask-for-help-list'),
    url(r'^report-bug/$', views.ReportBug.as_view(), name='report-bug'),
    url(r'^report-bug/list/$', views.ReportBugList.as_view(), name='report-bug-list'),

    url(r'^champions/(?P<pk>[0-9]+)/$', views.ChampionView.as_view(), name="champion-detail"),
    url(r'^champions/(?P<pk>[0-9]+)/delete/$', login_required(views.ConfirmDeleteChampion.as_view()), name="champion-delete"),
    url(r'^champions/all/$', views.AllChampionsView.as_view(), name="champions-all"),
    url(r'^champions/mine/$', login_required(views.MyChampionsView.as_view()), name="champions-mine"),
    url(r'^champions/new/$', login_required(views.NewChampionView.as_view()), name="champion-new"),

    url(r'^matches/(?P<pk>[0-9]+?)/$', views.MatchView.as_view(), name="match-detail"),
    url(r'^matches/(?P<pk>[0-9]+?)/dump/$', views.MatchDumpView.as_view(), name="match-dump"),
    url(r'^matches/all/$', views.AllMatchesView.as_view(), name="matches-all"),
    url(r'^matches/mine/$', login_required(views.MyMatchesView.as_view()), name="matches-mine"),
    url(r'^matches/new/$', login_required(views.NewMatchView.as_view()), name="match-new"),

    url(r'^status/$', views.MasterStatus.as_view(), name="status"),
]


if settings.STECHEC_USE_MAPS:
    urlpatterns += [
        url(r'^maps/(?P<pk>[0-9]+?)/$', views.MapView.as_view(), name="map-detail"),
        url(r'^maps/all/$', views.AllMapsView.as_view(), name="maps-all"),
        url(r'^maps/new/$', login_required(views.NewMapView.as_view()), name="map-new"),
    ]

python-lib/prologin/concours/stechec/views.py
from django.conf import settings
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.db import transaction
from django.db.models import Max, Min
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView, FormView, TemplateView, RedirectView
from django.views.generic.base import View
from django.views.generic.detail import SingleObjectMixin

import collections
import os
import socket
import urllib.parse

from prologin.concours.stechec import forms
from prologin.concours.stechec import models
# Use API throttling in the standard view
from prologin.concours.stechec.restapi.permissions import CreateMatchUserThrottle


class ChampionView(DetailView):
    context_object_name = "champion"
    model = models.Champion
    template_name = "stechec/champion-detail.html"

    @property
    def can_see_log(self):
        ch = self.get_object()
        return self.request.user == ch.author or self.request.user.is_staff

    def get_context_data(self, **kwargs):
        context = super(ChampionView, self).get_context_data(**kwargs)
        context['can_see_log'] = self.can_see_log
        return context


class ChampionsListView(ListView):
    context_object_name = "champions"
    paginate_by = 50
    template_name = "stechec/champions-list.html"
    title = "Tous les champions"

    def get_context_data(self, **kwargs):
        context = super(ChampionsListView, self).get_context_data(**kwargs)
        context['title'] = self.title
        context['user'] = self.request.user
        context['show_for_all'] = self.show_for_all
        context['explanation_text'] = self.explanation_text
        return context


class AllChampionsView(ChampionsListView):
    queryset = models.Champion.objects.filter(deleted=False)
    explanation_text = 'Voici la liste de tous les champions participant actuellement.'
    show_for_all = True


class MyChampionsView(ChampionsListView):
    explanation_text = 'Voici la liste de tous vos champions participant actuellement.'
    title = "Mes champions"
    show_for_all = False

    def get_queryset(self):
        user = self.request.user
        return models.Champion.objects.filter(deleted=False, author=user)


class MatchesListView(ListView):
    context_object_name = "matches"
    paginate_by = 100
    template_name = "stechec/matches-list.html"
    title = "Tous les matches"

    def get_context_data(self, **kwargs):
        context = super(MatchesListView, self).get_context_data(**kwargs)
        context['title'] = self.title
        context['user'] = self.request.user
        context['explanation_text'] = self.explanation_text
        context['show_creator'] = self.show_creator
        matches = []
        map_cache = {}
        for m in context['matches']:
            map_name = None
            map_id = None
            if settings.STECHEC_USE_MAPS:
                try:
                    map_id = int(m.map.split('/')[-1])
                    map_name = map_cache[map_id]
                except KeyError:
                    try:
                        map_cache[map_id] = map_name = models.Map.objects.get(pk=map_id).name
                    except Exception:
                        map_name = map_id
            matches.append((m, map_id, map_name))
        context['matches'] = matches
        return context


class MatchView(DetailView):
    context_object_name = "match"
    template_name = "stechec/match-detail.html"
    queryset = models.Match.objects.annotate(Max('matchplayer__score')).annotate(Min('matchplayer__id'))


class AllMatchesView(MatchesListView):
    queryset = models.Match.objects.all()
    explanation_text = "Voici la liste de tous les matches ayant été réalisés."
    show_creator = True


class MyMatchesView(MatchesListView):
    title = "Mes matches"
    explanation_text = "Voici la liste des matches que vous avez lancé."
    show_creator = False

    def get_queryset(self):
        return models.Match.objects.filter(author=self.request.user)


class AllMapsView(ListView):
    context_object_name = "maps"
    paginate_by = 100
    template_name = "stechec/maps-list.html"
    queryset = models.Map.objects.order_by('-official', '-id')


class MapView(DetailView):
    context_object_name = "map"
    template_name = "stechec/map-detail.html"
    model = models.Map


class NewChampionView(FormView):
    form_class = forms.ChampionUploadForm
    template_name = 'stechec/champion-new.html'

    def form_valid(self, form):
        champion = models.Champion(
            name=form.cleaned_data['name'],
            author=self.request.user,
            status='new',
            comment=form.cleaned_data['comment']
        )
        champion.save()
        # It's important to save() before sources =, as the latter needs the row id
        champion.sources = form.cleaned_data['tarball']

        return HttpResponseRedirect(champion.get_absolute_url())


class ConfirmDeleteChampion(DetailView):
    template_name = 'stechec/champion-delete.html'
    pk_url_kwarg = 'pk'
    model = models.Champion

    def get_object(self, queryset=None):
        return get_object_or_404(self.model,
                                 pk=self.kwargs[self.pk_url_kwarg],
                                 author=self.request.user)

    def post(self, request, *args, **kwargs):
        champion = self.get_object()
        champion.deleted = True
        champion.save()
        messages.success(request, "Champion {} supprimé.".format(champion.name))
        return HttpResponseRedirect(reverse('champions-mine'))


class NewMatchView(FormView):
    form_class = forms.MatchCreationForm
    template_name = 'stechec/match-new.html'

    def form_valid(self, form):
        throttler = CreateMatchUserThrottle()
        if not throttler.allow_request(self.request, self):
            messages.error(self.request,
                           "Vos requêtes sont trop rapprochées dans le temps. "
                           "Merci de patienter environ {:.0f} secondes avant de "
                            "recommencer votre requête.".format(throttler.wait()))
            return HttpResponseRedirect(reverse('match-new'))

        with transaction.atomic():
            match = models.Match(
                author=self.request.user,
                status='creating',
                tournament=None,
                options=''
            )
            if settings.STECHEC_USE_MAPS:
                match.map = form.cleaned_data['map'].path
            match.save()

            for i in range(1, settings.STECHEC_NPLAYERS + 1):
                champ = form.cleaned_data['champion_%d' % i]
                player = models.MatchPlayer(
                    champion=champ,
                    match=match
                )
                player.save()

            match.status = 'new'
            match.save()

        messages.success(self.request, "Le match #{} a été initié.".format(match.id))
        return HttpResponseRedirect(match.get_absolute_url())


class MatchDumpView(SingleObjectMixin, View):
    model = models.Match
    pk_url_kwarg = 'pk'

    def get(self, request, *args, **kwargs):
        match = self.get_object()
        h = HttpResponse(match.dump, content_type="application/stechec-dump")
        h['Content-Disposition'] = 'attachment; filename=dump-%s.json' % self.kwargs[self.pk_url_kwarg]
        h['Content-Encoding'] = 'gzip'
        return h


class NewMapView(FormView):
    form_class = forms.MapCreationForm
    template_name = 'stechec/map-new.html'

    def form_valid(self, form):
        map = models.Map(
            author=self.request.user,
            name=form.cleaned_data['name'],
            official=False
        )
        map.save()
        map.contents = form.cleaned_data['contents']
        return HttpResponseRedirect(map.get_absolute_url())


class MasterStatus(TemplateView):
    template_name = 'stechec/master-status.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            status = models.master_status()
            status = [(h, p, (100 * (m - s)) / m) for (h, p, s, m) in status]
            status.sort()
        except socket.error:
            status = None
        context['status'] = status
        return context


class RedmineIssueView(RedirectView):
    permanent = False

    tracker_id = None
    is_private = False
    subject = ""
    description = ""

    def get_redirect_url(self, *args, **kwargs):
        qs = {
            'issue[tracker_id]': str(self.tracker_id),
            'issue[is_private]': '1' if self.is_private else '0',
            'issue[subject]': self.subject,
            'issue[description]': self.description,
        }
        return '{}?{}'.format(settings.STECHEC_REDMINE_ISSUE_NEW,
                              urllib.parse.urlencode(qs))


class AskForHelp(RedmineIssueView):
    tracker_id = 3  # assistance
    is_private = True
    subject = "J'ai un problème : "


class ReportBug(RedmineIssueView):
    tracker_id = 1  # issue
    is_private = False
    subject = "[Remplacez ceci par un résumé court et explicite]"
    description = "\n\n".join([
        "*Où* est le problème (p. ex. adresse web, nom de la machine…) :",
        "*Comment* reproduire :",
        "Ce qui *devrait* se produire normalement :",
        "Ce qui *se produit* dans les faits :",
        ""
    ])


class RedmineIssueListView(RedirectView):
    permanent = False

    filters = []

    def get_redirect_url(self, *args, **kwargs):
        qs = collections.defaultdict(list)
        qs['set_filter'] = '1'
        for name, op, value in self.filters:
            qs['f[]'].append(str(name))
            qs['op[%s]' % name] = str(op)
            if value is not None:
                qs['v[%s][]' % name] = str(value)
        return '{}?{}'.format(settings.STECHEC_REDMINE_ISSUE_LIST,

python-lib/prologin/concours/stechec/templates/stechec/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" media="screen">
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css" media="screen">
  <link rel="stylesheet" href="{% static 'css/theme.css' %}" type="text/css" media="screen" title="Theme">
  <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" media="screen" title="Main">
  {% block head %}{% endblock %}

  <title>{% block title %}SANS TITRE{% endblock %} – Prologin</title>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <img alt="Prologin" src="{% static 'img/logo-cube.png' %}">
      </a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'v1:api-root' %}" title="API REST"><i class="fa fa-code"></i> API</a></li>
      {% if request.user.is_authenticated %}
        {% comment %}
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              {{ request.user.username }}<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li>some item</li>
            </ul>
          </li>
        {% endcomment %}
        <li><a href="#"><i class="fa fa-user"></i> {{ request.user.username }}</a></li>
        {% if request.user.is_staff %}
          <li><a href="{% url 'admin:index' %}" title="Administration"><i class="fa fa-wrench"></i> Admin</a></li>
        {% endif %}
      {% else %}
        <li><a href="{% url 'login' %}"><i class="fa fa-user"></i> Connexion</a></li>
      {% endif %}
    </ul>
  </div>
</nav>

<div class="container">

  <div class="row">

    <div class="col-sm-3" role="complementary">
      {# Side menu #}
      <h1 class="hidden-xs">&nbsp;</h1> {# hack to align menu with content #}
      {% include "stechec/nav-menu.html" %}
    </div>
    <div class="col-sm-9" role="main">

      {# Content #}
      <div id="content">
        <h1>{% block titleh1 %}{% endblock %}</h1>

            {% for message in messages %}
              <p class="alert-dismissible alert alert-{% if message.tags == 'error' %}danger{% elif message.tags %}{{ message.tags }}{% endif %}">
                <button type="button" class="close" data-dismiss="alert" aria-label="Cacher">
                  <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
              </p>
            {% endfor %}

        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
</div>

<script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

python-lib/prologin/concours/stechec/templates/stechec/champion-delete.html
{% extends "stechec/base.html" %}

{% block title %}Suppression du champion{% endblock %}
{% block titleh1 %}Suppression du champion {{ object.name }} <small>#{{ object.id }}</small>{% endblock %}

{% block content %}

<p>Confirmez la suppression de votre champion&nbsp;:</p>

<form action="" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger"><i class="fa fa-trash-o"></i> Supprimer {{ object.name }}</button>
</form>

{% endblock %}

python-lib/prologin/concours/stechec/templates/stechec/champion-detail.html
{% extends "stechec/base.html" %}
{% load static %}

{% block title %}{{ champion.name }} – Champion{% endblock %}
{% block titleh1 %}Détails du champion {{ champion.name }} <small>#{{ champion.id }}</small>{% endblock %}

{% block content %}

  <div class="row">
      <div class="col-sm-6">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Champion</h3>
        </div>
        <div class="panel-body">
          <dl class="dl-horizontal dl-narrow">
            <dt>ID</dt><dd>{{ champion.id }}</dd>
            <dt>Auteur</dt><dd>{{ champion.author }}</dd>
            <dt>État</dt><dd>{% include "stechec/stub_status_champion.html" %}</dd>
          </dl>
        </div>
      </div>
    </div><div class="col-sm-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Commentaires</h3>
        </div>
        <div class="panel-body">
          {{ champion.comment|linebreaksbr|default:"<em>Aucun commentaire.</em>" }}
        </div>
      </div>
    </div>
  </div>

  {% if champion.compilation_log and can_see_log %}
    <p>
      <button class="btn btn-default btn-small" data-role="toggler" data-target="#log"><i class="fa"></i> <span>Afficher</span> le log de
        compilation
      </button>
    <pre id="log">{{ champion.compilation_log }}</pre>
  {% endif %}

{% endblock %}

{% block extra_js %}
  <script src="{% static 'js/uitools.js' %}" type="text/javascript"></script>
{% endblock %}

python-lib/prologin/concours/stechec/templates/stechec/home.html
{% extends "stechec/base.html" %}

{% block title %}Accueil{% endblock %}
{% block titleh1 %}Bienvenue
  <small>{{ request.user.get_full_name }}</small>{% endblock %}

{% block content %}

  <div class="row">
    {% if request.user.is_authenticated %}
      <div class="col-lg-4">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Le concours</h3>
          </div>
          <div class="panel-body">
            <h4>Besoin d'aide&nbsp;?</h4>

            <div class="btn-group" role="group">
              <a href="{% url 'ask-for-help' %}" class="btn btn-default"><i class="fa fa-bell"></i> Demander de
                l'aide</a>
              <a href="{% url 'ask-for-help-list' %}" class="btn btn-default" title="Toutes mes demandes d'aide"><i
                class=" fa fa-list"></i></a>
            </div>

            <h4>Un bug trouvé&nbsp;?</h4>

            <div class="btn-group" role="group">
              <a href="{% url 'report-bug' %}" class="btn btn-default"><i class="fa fa-bug"></i> Signaler un
                problème</a>
              <a href="{% url 'report-bug-list' %}" class="btn btn-default" title="Tous mes signalements de bug"><i
                class=" fa fa-list"></i></a>
            </div>
          </div>
        </div>
      </div>
    {% endif %}

    {% comment %}
    <div class="col-lg-4">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Liens utiles</h3>
        </div>
        <div class="panel-body">
          <ul class="nav">
            {# TODO: actual links #}
            <li><a href="#">Lien utile</a></li>
            <li><a href="#">Lien utile</a></li>
            <li><a href="#">Lien utile</a></li>
          </ul>
        </div>
      </div>
    </div>

    {% if request.user.is_authenticated %}
      <div class="col-lg-4">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Ma participation</h3>
          </div>
          <div class="panel-body">
            <dl class="dl-horizontal dl-narrow">
              {# TODO: actual stats #}
              <dt>4</dt>
              <dd>champions</dd>
              <dt>12</dt>
              <dd>matchs</dd>
              <dt>4</dt>
              <dd>victoires</dd>
            </dl>
          </div>
        </div>
      </div>
    {% endif %}
    {% endcomment %}

  </div>

{% endblock %}

python-lib/prologin/concours/stechec/templates/stechec/map-detail.html
{% extends "stechec/base.html" %}

{% block title %}Carte {{ map.name }}{% endblock %}
{% block titleh1 %}Carte {{ map.name }}
  <small>#{{ map.id }}</small>{% endblock %}

{% block content %}

  {% if map.official %}
    <p><i class=" fa fa-star text-warning"></i> Cette carte est officielle.</p>
  {% endif %}
  <p>
    Envoyée par <strong>{{ map.author }}</strong>.
  </p>

  <h3>Aperçu de la carte</h3>

  <pre>{{ map.contents }}</pre>

{% endblock %}

python-lib/prologin/concours/stechec/templates/stechec/maps-list.html
{% extends "stechec/base.html" %}

{% block title %}Toutes les cartes{% endblock %}
{% block titleh1 %}Toutes les cartes{% endblock %}

{% block content %}

<p class="intro">Cette page liste toutes les maps créées par les organisateurs et candidats du concours.</p>

{% if is_paginated %}{% load paginator %}{% paginator 5 %}{% endif %}

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Officielle</th>
            <th>Nom</th>
            <th>Auteur</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for map in maps %}
        <tr class="{% cycle "row1" "row2" %}{% if map.official %} official{% endif %}">
            <td>{{ map.id }}</td>
            <td>
                {% if map.official %}
                Oui <i class="fa fa-star text-warning"></i>
                {% else %}
                Non
                {% endif %}
            </td>
            <td>{{ map.name }}</td>
            <td>{{ map.author }}</td>
            <td><a href="{{ map.get_absolute_url }}" class="btn btn-default btn-xs"><i class="fa fa-info"></i> Détails</a></td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4" class="text-muted"><i class="fa fa-frown-o"></i> Aucune carte n'est disponible pour le moment.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

python-lib/prologin/concours/stechec/templates/stechec/master-status.html
{% extends "stechec/base.html" %}
{% load static %}

{% block title %}État des serveurs{% endblock %}
{% block titleh1 %}État des serveurs{% endblock %}

{% block head %}
{% endblock %}

{% block content %}

  <p class="intro">Cette page donne un aperçu de la charge des serveurs de la finale.</p>

  {% if status == None %}
    <p class="alert alert-danger">
      <i class="fa fa-warning"></i> Le serveur de répartition de tâches sur le cluster (<em>masternode</em>) est
      inaccessible.
    </p>
  {% endif %}

  <table class="table table-striped">
    <thead>
    <tr>
      <th>Serveur</th>
      <th>Utilisation</th>
    </tr>
    </thead>
    <tbody>
    {% for host, port, usage in status %}
      <tr>
        <td style="vertical-align: middle;"><tt><strong>{{ host }}</strong>:{{ port }}</tt></td>
        <td>
          <div class="progress no-margin">
            <div class="progress-bar progress-bar-{% if usage > 80 %}danger{% elif usage > 50 %}warning{% else %}success{% endif %}" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"
                 style="width: {{ usage }}%;">
              <span class="{% if usage < 10 %}narrow{% endif %}">{{ usage }}%</span>
            </div>
          </div>
        </td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="2" class="text-muted"><i class="fa fa-frown-o"></i> Aucun serveur trouvé.</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock %}

python-lib/prologin/concours/stechec/templates/stechec/match-detail.html
{% extends "stechec/base.html" %}
{% load humanize static substract %}

{% block title %}Détail du match{% endblock %}
{% block titleh1 %}Détail du match <small>#{{ match.id }}</small>{% endblock %}

{% block content %}

  <div class="row">
    <div class="col-sm-6">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Match</h3>
        </div>
        <div class="panel-body">
          <dl class="dl-horizontal dl-narrow">
            <dt>ID</dt>
            <dd>{{ match.id }}</dd>
            <dt>État</dt>
            <dd>{% include "stechec/stub_status_match.html" %}</dd>
            <dt>Initié</dt>
            <dd>{{ match.ts|naturalday }} à {{ match.ts|time:"H:i:s" }}</dd>
            <dt>par</dt>
            <dd>{{ match.author }}</dd>
          </dl>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Replay</h3>
        </div>
        <div class="panel-body">
          {% if match.is_done %}
            <a href="{% url "match-dump" match.id %}" class="btn btn-default btn-block">
              <i class="fa fa-download"></i> Télécharger</a>
          {% else %}
            <em>Le match n'est pas encore terminé.</em>
          {% endif %}
        </div>
      </div>
    </div>
  </div>

  <h2>Participants</h2>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>UID</th>
      <th>ID champion</th>
      <th>Champion</th>
      <th>Score</th>
      <th>Log</th>
    </tr>
    </thead>
    <tbody>
    {% for player in match.matchplayer_set.all %}
      <tr class="{% cycle "row1" "row2" %}">
        <td>{{ player.id|substract:match.matchplayer__id__min }}</td>
        <td>{{ player.champion.id }}</td>
        <td>{{ player.champion }}</td>
        {% if match.is_done %}
          <td>{{ player.score }}</td>
          <td>
            {% if request.user == match.champion.author or request.user.is_staff %}
              <button data-role="toggler" data-target="#log-{{ player.id }}" class="btn btn-default btn-xs">
                <i class="fa"></i> <span>Afficher</span> le log
              </button>
              <pre id="log-{{ player.id }}">{{ player.log }}</pre>
            {% endif %}
          </td>
        {% else %}
          <td colspan="2"><i class="fa fa-clock-o"></i> <em> Match non terminé</em></td>
        {% endif %}
      </tr>
    {% endfor %}
    </tbody>
  </table>

  {% if request.user.is_staff %}
    <p><button class="btn btn-default" data-role="toggler" data-target="#serv-log"><i class="fa"></i> <span>Afficher</span> le log serveur</button></p>
    <pre id="serv-log">{{ match.log }}</pre>
  {% endif %}

  {% if settings.STECHEC_REPLAY %}
    <div id="replay">
      <canvas id="replay_canvas" width="0" height="0"></canvas>
      <br/>
      <aside>
        <div>
          <button class="replay_btn" type="button" onclick="replay_play();">Jouer</button>
          <button class="replay_btn" type="button" onclick="replay_pause();">Pause</button>
          <br/><br/>
          <input id="replay_turn" type="range" value="0" min="0" max="0"
                 onchange="replay_update()"/>
          Tour : <span id="replay_lbl_turn">0</span>
          <br/>
        </div>

        {% for player in match.matchplayer_set.all %}
          <div id="replay_p{{ player.id }}"></div> <br/>
        {% endfor %}
      </aside>
    </div>
  {% endif %}

{% endblock %}

{% block extra_js %}
  <script type="text/javascript" src="{% static 'js/uitools.js' %}"></script>
  {% if settings.STECHEC_REPLAY %}
    <script type="text/javascript" src="{% static 'replay/replay.js' %}"></script>
    <script type="text/javascript">
      replay_init();
    </script>
  {% endif %}
{% endblock %}

python-lib/prologin/concours/stechec/templates/stechec/stub_status_champion.html
{% if champion.status == 'new' %}
<i class="champ-status fa fa-clock-o"></i>
{% elif champion.status == 'pending' %}
<i class="champ-status fa fa-cogs"></i>
{% elif champion.status == 'ready' %}
<i class="champ-status fa fa-check"></i>
{% elif champion.status == 'error' %}
<i class="champ-status fa fa-times"></i>
{% endif %}
{{ champion.get_status_display }}

python-lib/prologin/concours/stechec/templates/stechec/stub_status_match.html
{% if match.status == 'creating' %}
<i class="champ-status fa fa-clock-o"></i>
{% elif match.status == 'new' %}
<i class="champ-status fa fa-clock-o"></i>
{% elif match.status == 'pending' %}
<i class="champ-status fa fa-cogs"></i>
{% elif match.status == 'done' %}
<i class="champ-status fa fa-check"></i>
{% endif %}
{{ match.get_status_display }}